### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Amit-Sagar**
I am adding a  Redis cloud platform where we can earn free t-shirts

### CODE REVIEW

**Comment by Joonsang1994** [comment]
@Amit-Sagar Where is it mentioned in the link?

**Comment by Amit-Sagar** [comment]
I add the full details in the last of read.md

**Comment by Amit-Sagar** [comment]
@Joonsang1994 I added the whole details in  the last of README.md file

**Comment by Joonsang1994** [comment]
No, I mean to say where does it mention about the swag in the link?

**Comment by Amit-Sagar** [comment]
@Joonsang1994 yes ! I added the t-shirt image URL and the Url where we get the t-shirt

**Comment by Amit-Sagar** [comment]
@Joonsang1994  please check line 275 to 279 in README.md file

**Comment by Joonsang1994** [comment]
https://redislabs.com/try-free/. In this link, where does it mention about the swag?

**Comment by Amit-Sagar** [comment]
yes!

**Comment by Amit-Sagar** [comment]
go to the link signup and create your first database you will get a free T-shirt.

**Comment by Joonsang1994** [comment]
I had registered previously, I have registered again, but I didn't get any intimation regarding a tshirt. Have you got one? Can you share any link/screen shot where it mentions that you will get a tshirt?

**Pull request closed without merging**
